[package]
name = "mundis-cargo-build-bpf"
version = "1.9.14"
description = "Compile a local package and all of its dependencies using the Mundis BPF SDK"
authors = ["Mundis Maintainers <maintainers@mundis.io>"]
repository = "https://github.com/mundisnetwork/axis"
homepage = "https://mundis.io/"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
bzip2 = "0.4.3"
clap = "2.33.3"
regex = "1.5.4"
cargo_metadata = "0.14.1"
mundis-sdk = { path = "..", version = "=1.9.14" }
mundis-download-utils = { path = "../../download-utils", version = "=1.9.14" }
tar = "0.4.37"

[dev-dependencies]
serial_test = "*"

[features]
program = []

[[bin]]
name = "cargo-build-bpf"
path = "src/main.rs"
