[package]
name = "anima-token-account"
version = "1.0.3"
authors = ["Mundis Maintainers <maintainers@mundis.io>"]
repository = "https://github.com/mundisnetwork/axis"
license = "Apache-2.0"
edition = "2018"

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
mundis-program = { path = "../../sdk/program", version = "=1.9.14" }
anima-token = { version = "3.2", path = "../token", features = ["no-entrypoint"] }

[dev-dependencies]
mundis-program-test = { path = "../../program-test", version = "=1.9.14" }
mundis-sdk = { path = "../../sdk", version = "=1.9.14" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
