[package]
name = "mundis-token-program"
version = "1.9.14"
authors = ["Mundis Maintainers <maintainers@mundis.io>"]
repository = "https://github.com/mundisnetwork/axis"
license = "Apache-2.0"
homepage = "https://mundis.io/"
edition = "2021"


[dependencies]
arrayref = "0.3.6"
num-derive = "0.3"
num-traits = "0.2"
num_enum = "0.5.1"
mundis-program = { path = "../../sdk/program", version = "=1.9.14" }
thiserror = "1.0"

[dev-dependencies]
mundis-sdk = { path = "../../sdk", version = "=1.9.14" }