[package]
name = "mundis-cargo-test-bpf"
version = "1.9.14"
description = "Execute all unit and integration tests after building with the BPF SDK"
authors = ["Mundis Maintainers <maintainers@mundis.io>"]
repository = "https://github.com/mundisnetwork/axis"
homepage = "https://mundis.io/"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
clap = "2.33.3"
cargo_metadata = "0.14.1"

[[bin]]
name = "cargo-test-bpf"
path = "src/main.rs"
