[package]
name = "anima-memo"
version = "3.0.1"
authors = ["Mundis Maintainers <maintainers@mundis.io>"]
repository = "https://github.com/mundisnetwork/axis"
license = "Apache-2.0"
edition = "2018"

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
mundis-program = { path = "../../sdk/program", version = "=1.9.14" }

[dev-dependencies]
mundis-sdk = { path = "../../sdk", version = "=1.9.14" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
