[package]
name = "mundis-program-test"
version = "1.9.14"
authors = ["Mundis Maintainers <maintainers@mundis.io>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/mundisnetwork/axis"

[dependencies]
async-trait = "0.1.51"
base64 = "0.12.3"
bincode = "1.3.3"
chrono-humanize = "0.2.1"
log = "0.4.14"
serde = "1.0.130"
mundis-banks-client = { path = "../banks-client", version = "=1.9.14" }
mundis-banks-server = { path = "../banks-server", version = "=1.9.14" }
mundis-bpf-loader-program = { path = "../programs/bpf_loader", version = "=1.9.14" }
mundis-logger = { path = "../logger", version = "=1.9.14" }
mundis-program-runtime = { path = "../program-runtime", version = "=1.9.14" }
mundis-runtime = { path = "../runtime", version = "=1.9.14" }
mundis-sdk = { path = "../sdk", version = "=1.9.14" }
mundis-vote-program = { path = "../programs/vote", version = "=1.9.14" }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
assert_matches = "1.5.0"
