[package]
name = "mundis-program-test"
version = "1.9.14"
authors = ["Mundis Maintainers <maintainers@mundis.io>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/mundisnetwork/axis"

[dependencies]
borsh = "0.9.1"
futures = "0.3"
async-trait = "0.1.51"
base64 = "0.12.3"
bincode = "1.3.3"
chrono-humanize = "0.2.1"
log = "0.4.14"
serde = "1.0.130"
mundis-logger = { path = "../logger", version = "=1.9.14" }
mundis-program-runtime = { path = "../program-runtime", version = "=1.9.14" }
mundis-program = { path = "../sdk/program", version = "=1.9.14" }
mundis-runtime = { path = "../runtime", version = "=1.9.14" }
mundis-sdk = { path = "../sdk", version = "=1.9.14" }
mundis-vote-program = { path = "../programs/vote", version = "=1.9.14" }
mundis-send-transaction-service = { path = "../send-transaction-service", version = "=1.9.14" }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
tokio-serde = { version = "0.8", features = ["bincode"] }
tokio-stream = "0.1"
tarpc = { version = "0.27.2", features = ["full"] }

[dev-dependencies]
assert_matches = "1.5.0"
